# One Hot Encoding

In [3]:
from sklearn.preprocessing import OneHotEncoder
import numpy
document = "my name is sunny and I love AI"
print(document)
documents = ["people watch movie", 
             "people watch cricket", 
             "people like movie", 
             "people like cricket"]
print(documents)
tokens = [sentence.lower().split() for sentence in documents]
tokens
all_words = [[word] for sentence in tokens for word in sentence]
print(all_words)
encoder = OneHotEncoder(sparse_output=False)
encoder.fit(all_words)
encoder.categories_
print("Vocabulary:", encoder.categories_[0])
tokens
for sentence in tokens:
    print(sentence)
for sentence in tokens:
    encoded_sentence = encoder.transform([[word] for word in sentence])
    print("\nSentence:", sentence)
    print(encoded_sentence)

my name is sunny and I love AI
['people watch movie', 'people watch cricket', 'people like movie', 'people like cricket']
[['people'], ['watch'], ['movie'], ['people'], ['watch'], ['cricket'], ['people'], ['like'], ['movie'], ['people'], ['like'], ['cricket']]
Vocabulary: ['cricket' 'like' 'movie' 'people' 'watch']
['people', 'watch', 'movie']
['people', 'watch', 'cricket']
['people', 'like', 'movie']
['people', 'like', 'cricket']

Sentence: ['people', 'watch', 'movie']
[[0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0.]]

Sentence: ['people', 'watch', 'cricket']
[[0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0.]]

Sentence: ['people', 'like', 'movie']
[[0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]

Sentence: ['people', 'like', 'cricket']
[[0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0.]]


##### sparse_output=False means the encoder returns a NumPy array instead of a sparse matrix. This makes the output easier

https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.OneHotEncoder.html